#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Download Google Fonts locally (self-host) into assets/fonts/ and write assets/fonts.css.

Run from the repo root:
    python tools/fetch_fonts.py
"""

import os
import re
import sys
import time

import requests

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FONT_DIR = os.path.join(ROOT, "assets", "fonts")
CSS_OUT = os.path.join(ROOT, "assets", "fonts.css")
CSS_URL = (
    "https://fonts.googleapis.com/css2?"
    "family=Cormorant+Garamond:ital,wght@0,500;0,700;1,500;1,700"
    "&family=Noto+Serif+SC:wght@700;900&display=swap"
)
UA = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
    "(KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
)


def slug(s):
    return re.sub(r"[^a-z0-9]+", "", s.lower())


def main():
    os.makedirs(FONT_DIR, exist_ok=True)
    css = requests.get(CSS_URL, headers={"User-Agent": UA}, timeout=60).text
    blocks = re.findall(r"@font-face\s*\{([^}]*)\}", css)
    if not blocks:
        sys.exit("no @font-face blocks found")

    out = []
    counters = {}
    total = 0
    n_files = 0
    for block in blocks:
        family = re.search(r"font-family:\s*['\"]?([^;'\"}]+)['\"]?\s*;", block)
        style = re.search(r"font-style:\s*([^;]+);", block)
        weight = re.search(r"font-weight:\s*([^;]+);", block)
        src = re.search(r"url\((https://[^)]+)\)\s*format\(['\"]woff2['\"]\)", block)
        if not (family and style and weight and src):
            continue

        family = family.group(1).strip()
        style = style.group(1).strip()
        weight = weight.group(1).strip()
        url = src.group(1)
        key = (slug(family), weight, style)
        counters[key] = counters.get(key, 0) + 1
        fname = f"{slug(family)}-{weight}-{style}-{counters[key]:03d}.woff2"
        fpath = os.path.join(FONT_DIR, fname)

        if not os.path.exists(fpath) or os.path.getsize(fpath) == 0:
            data = requests.get(url, headers={"User-Agent": UA}, timeout=120).content
            with open(fpath, "wb") as f:
                f.write(data)
            time.sleep(0.05)

        total += os.path.getsize(fpath)
        n_files += 1
        new_block = block.replace(url, f"fonts/{fname}")
        if "font-display" not in new_block:
            new_block += "\n  font-display: swap;"
        out.append("@font-face {" + new_block + "}")
        print(f"{fname}\t{os.path.getsize(fpath)}")

    with open(CSS_OUT, "w", encoding="utf-8") as f:
        f.write(
            "/* Self-hosted Google Fonts (SIL Open Font License) "
            "- generated by tools/fetch_fonts.py */\n"
        )
        f.write("\n".join(out) + "\n")

    print(f"files={n_files} bytes={total} ({total / 1024 / 1024:.1f} MiB)")
    print(f"css={CSS_OUT}")


if __name__ == "__main__":
    main()
